from .node.code_fence_node import CodeFenceNode
from .node.node import Node
from .node.br_node import BrNode
from .mark import Mark
from .node.tag_node import TagNode
from .node.text_node import TextNode
from .node.user_mention_node import UserMentionNode
from .node.attachment_node import AttachmentNode
from .node.image_node import ImageNode

from typing import Iterable

from bs4 import NavigableString, Stylesheet
import re

"""
Check whether a tag is matched by a CSS query.
"""


def tag_matches(tag, query):
    return tag.css.closest(query) == tag


def sane_children(children, correct_types=True):
    children = [child for child in children if child is not None]
    c = []
    for child in children:
        if isinstance(child, Iterable):
            for gc in child:
                c.append(gc)
        else:
            c.append(child)

    children = c

    if not correct_types:
        return children
    if len(children) == 1:
        return children[0]
    if len(children) == 0:
        return None
    return children


"""
Returns either a single node or a list of nodes.
A list of nodes is only returned if the tree contained a mark
with more than 1 child.
May return None for nodes that are to be omitted from the final document.
"""


def node_factory(tag, marks):
    if not tag:
        return None

    # whyever that would happen
    if type(tag) is Stylesheet:
        return None

    if type(tag) is NavigableString:
        if len(tag.string) == 0 or tag.string == "":
            return None
        return TextNode(tag.string, marks)

    # Formatting is applied as marks, so it needs to be handled first
    if tag.name in ["b", "s", "strike", "del", "u", "i", "em", "code", "strong"]:
        # marks.append(mark_factory(tag))
        processedNodes = []
        for child in tag.children:
            processedNodes.append(node_factory(child, marks + [mark_factory(tag)]))
        return sane_children(processedNodes)

    # We process the children recursively, building the tree for Outline.
    children = []
    for child in tag.children:
        c = node_factory(child, marks)
        if type(c) is list:
            children += c
        else:
            children.append(c)
    # Remove None entries
    children = sane_children(children, False)

    # Headings processing can be grouped together
    if tag.name in ["h1", "h2", "h3", "h4"]:
        return TagNode(
            "heading", "block", ("inline", 0), children, {"level": int(tag.name[1])}
        )

    if tag.name in ["th", "td"]:
        colspan = int(tag["colspan"]) if "colspan" in tag.attrs else 1
        rowspan = int(tag["rowspan"]) if "rowspan" in tag.attrs else 1

        # Known issue: This will set alignment to the first specified one, not the last.
        # Since this HTML is generated by Confluence, we assume it not to set two different alignments
        # on the same table cell
        if "style" in tag.attrs:
            align = re.match(r"text-align: ([a-zA-Z]+);", tag["style"])
            if align and align.group(1):
                align = align.group(1)
            else:
                align = None
        else:
            align = None  # Set default null/None

        conf = {"colspan": colspan, "rowspan": rowspan, "alignment": align}
        if len(children) == 0:
            children = [produce_paragraph()]
        return TagNode(tag.name, tag.name, ("block", 0), children, conf)

    # We then need to make sure every case is covered.
    # For anything else, we return None as to not consider it.
    match tag.name:
        case "a":
            if len(children) == 0:
                return None

            if tag_matches(tag, "a.confluence-userlink"):
                return UserMentionNode(tag.get_text(), tag["data-username"])

            if tag_matches(tag, "a.confluence-embedded-file"):
                title = (
                    tag["aria-label"]
                    if "aria-label" in tag.attrs and tag["aria-label"] != ""
                    else None
                )
                suffix = (
                    tag["data-linked-resource-default-alias"].split(".")[-1]
                    if "." in tag["data-linked-resource-default-alias"]
                    else ""
                )
                confluenceId = tag["data-linked-resource-id"] + "." + suffix
                confluenceDoc = tag["data-linked-resource-container-id"]
                return AttachmentNode(title, confluenceId, confluenceDoc)

            # We omit user logos
            if tag_matches(tag, "a.user-logo-link"):
                return None

            # This only handles text links properly, and doesn't apply inner formatting
            # That is intentional - Outline can't handle images as link "text", and changing the appearance of a link isn't that important
            if tag.get_text(strip=True) == "":
                return None

            add_link_mark = (
                [
                    Mark(
                        "link",
                        {
                            "href": (
                                tag["href"].replace(" ", "%20") if tag["href"] else ""
                            )
                        },
                    )
                ]
                if "href" in tag.attrs
                else []
            )

            return TextNode(
                tag.get_text(strip=True),
                marks + add_link_mark,
            )

        case "body":
            return TagNode("doc", "doc", ("block", 1), children)

        case "br":
            return BrNode()

        case "button":
            return TagNode("paragraph", "block", ("inline", 0), children)

        case "div":
            validInNotice = (
                "list blockquote hr paragraph heading code_block code_fence attachment"
            )
            # Some boxes can be imported into Outline, so we need to handle the special divs.
            if tag_matches(tag, "div.confluence-information-macro-information"):
                return TagNode(
                    "container_notice",
                    "block",
                    ("block", 1),
                    children,
                    {"style": "info"},
                )

            if tag_matches(tag, "div.confluence-information-macro-tip"):
                return TagNode(
                    "container_notice",
                    "block",
                    ("block", 1),
                    children,
                    {"style": "tip"},
                )

            if tag_matches(tag, "div.confluence-information-macro-note"):
                return TagNode(
                    "container_notice",
                    "block",
                    ("block", 1),
                    children,
                    {"style": "success"},
                )

            if tag_matches(tag, "div.confluence-information-macro-warning"):
                return TagNode(
                    "container_notice",
                    "block",
                    ("block", 1),
                    children,
                    {"style": "warning"},
                )

            # Not all divs produce good output. Some are wholly unnecessary.
            # The unnecessary ones are filtered here.
            if (
                tag_matches(tag, "div.update-item-icon")
                or tag_matches(tag, "div.update-item-profile")
                or tag_matches(tag, "div.more-link-container")
            ):
                return None

            # Every other div is just wrapping,
            return sane_children(children)

        case "hr":
            return TagNode("hr", "block", ("none", 0), [])

        case "img":
            alt = str(tag["alt"]) if "alt" in tag.attrs and tag["alt"] != "" else None
            width = int(tag["width"]) if "width" in tag.attrs else 250
            height = int(tag["height"]) if "height" in tag.attrs else 250
            return ImageNode(tag["src"], width, height, alt)

        case "li":
            if len(children) == 0:
                children = [produce_paragraph()]
            if tag_matches(tag, "li[data-inline-task-id]"):
                checked = "class" in tag.attrs and "checked" in tag["class"]
                # Sometimes, Confluence gets confused
                if tag["data-inline-task-id"]:
                    return TagNode(
                        "checkbox_item",
                        "checkbox_item",
                        ("block", 1),
                        children,
                        {"checked": checked},
                    )

            return TagNode("list_item", "list_item", ("block", 1), children)

        case "ol":
            return TagNode("ordered_list", "block", ("list_item", 1), children)

        case "p":
            if len(children) == 1 and children[0].node_type == "br":
                return None
            if len(children) == 1 and children[0].node_type == "attachment":
                return children[0]
            return TagNode("paragraph", "block", ("inline", 0), children)

        case "pre":
            languages = (
                [a for a in tag.attrs["class"] if a.startswith("language-")]
                if "class" in tag.attrs
                else []
            )
            # Should never be more than 1. If it somehow is, we don't set it
            lang = (
                languages[0].replace("language-", "") if len(languages) == 1 else None
            )

            # We use JavaScript as fallback.
            if not lang:
                lang = "javascript"

            # These are named differently in Confluence vs. Outline
            if lang == "shell":
                lang = "bash"

            if not tag.get_text():
                return None
            children = [TextNode(tag.get_text(), [])]
            return CodeFenceNode(children, lang)

        case "span":
            if tag_matches(tag, "span.aui-avatar") or tag_matches(tag, "span.aui-icon"):
                return None

            if tag_matches(tag, "span.confluence-embedded-file-wrapper"):
                return children[0]

            # Most spans are just wrapping.
            return sane_children(children)

        case "table":
            # That table is empty and screws up imports, so we do not consider it.
            if tag_matches(tag, "table.profile-full"):
                return None

            return TagNode("table", "block", ("tr", 1), children)

        case "thead":
            return sane_children(children)

        case "tbody":
            return sane_children(children)

        case "time":
            return sane_children(children)

        case "tr":
            return TagNode("tr", "tr", ("th td", 0), children)

        case "ul":
            # We don't want lists without items
            if len(children) == 0:
                return None

            if tag_matches(tag, "ul[data-inline-tasks-content-id]") or tag_matches(
                tag, "ul.inline-task-list"
            ):
                return TagNode("checkbox_list", "block", ("checkbox_item", 1), children)

            return TagNode("bullet_list", "block", ("list_item", 1), children)

        # catches: input, fieldset
        case _:
            return None  # TagNode(tag.name, 'invalid', ('none', 0), children)


def produce_paragraph(children=[]):
    return TagNode("paragraph", "block", ("inline", 0), children)


"""
Creates Marks based on the current tag.
"""


def mark_factory(tag):
    match tag.name:
        case "b":
            return Mark("strong")

        case "code":
            return Mark("code_inline")

        case "del":
            return Mark("strikethrough")

        case "i":
            return Mark("em")

        case "s":
            return Mark("strikethrough")

        case "strike":
            return Mark("strikethrough")

        case "u":
            return Mark("underline")

        case _:
            return Mark(tag.name)
